### ISSUE TITLE
Welome Raymond

### ISSUE THREAD

**Issue by askdebb** [askdebb/printf#1]
We are about to start, hope you are ready. Get your sandbox active. We move!

**Comment by askdebb** [comment]
Let me know when ready so we start the tasks.

**Comment by Magma4** [comment]
> Let me know when ready so we start the tasks.



> 

Ready bro

**Comment by askdebb** [comment]
ok, so the project has one mandatory task and 14 advanced tasks. We can alternate them, i will start with the first task then you continue.

**Comment by Magma4** [comment]
okay bro

**Comment by askdebb** [comment]
main.h first

**Comment by askdebb** [comment]
we are to put main.c in folder named test

**Comment by askdebb** [comment]
i merge our already created branches, now lets creates new ones.
mine: chris_branch
yours: raymond_branch

**Comment by Magma4** [comment]
we should create new branches?

**Comment by Magma4** [comment]
so each task we create new branches?

**Comment by askdebb** [comment]
n

> we should create new branches?

no

**Comment by Magma4** [comment]
oh okay

**Comment by askdebb** [comment]
> so each task we create new branches?

no please, the branch will be used for all your tasks and later we merge, i'm also doing same here. if you have noticed i just push my branch with main.h file and a readme file, from my terminal.

**Comment by askdebb** [comment]
> oh okay

I'm about to push my test folder

**Comment by Magma4** [comment]
I don't see your new branch..i just see the readme and file

**Comment by askdebb** [comment]
> I don't see your new branch..i just see the readme and file

in your terminal?, you can fetch or pull. and you can check branch and you will see it there by the side of  CODE

**Comment by Magma4** [comment]
naa on github

**Comment by askdebb** [comment]
> naa on github

okay, i've seen your branch and your files, great work!

**Comment by Magma4** [comment]
Great work too bro

**Comment by Magma4** [comment]
On to the next

**Comment by askdebb** [comment]
Project done
